// src/js/constants/action-types.js

export const UPDATE_TABLE_INPUT = "UPDATE_TABLE_INPUT";
export const UPDATE_SELECTED_CURRENCY = "UPDATE_SELECTED_CURRENCY";
export const UPDATE_PERCENTAGE_BOX = "UPDATE_PERCENTAGE_BOX";
export const UPDATE_PREDICTION_POINT = "UPDATE_PREDICTION_POINT";
export const UPDATE_CURRENCY_BASE = "UPDATE_CURRENCY_BASE";
export const DATA_LOADED = "DATA_LOADED";
export const ADD_PREDICTION_POINTS = "ADD_PREDICTION_POINTS";
